--- #YAML:1.0
name:                     Labyrinth::DIUtils::GD
version:                  5.04
abstract:                 Digital Image utilities driver with GD for Labyrinth Framework
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  GD:                               0,
recommends:
  Test::More:                       0.70
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
  Test::CPAN::Meta:                 0.13
  Test::JSON::Meta:                 0.08
build_requires:
  Test::More:                       0.01

provides:
  Labyrinth::DIUtils::GD:
    file:     lib/Labyrinth/DIUtils/GD.pm
    version:  5.04

no_index:
  directory:
    - t

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-DIUtils-GD

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
