--- #YAML:1.0
name:                     Labyrinth-DIUtils-GD
version:                  5.08
abstract:                 Digital Image utilities driver with GD for Labyrinth Framework
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                             5.006
  GD:                               0
  IO::File:                         0
recommends:
  Test::CPAN::Meta:                 0
  Test::CPAN::Meta::JSON:           0
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
build_requires:
  File::Copy:                       0
  File::Path:                       0
  Test::More:                       0.01

provides:
  Labyrinth::DIUtils::GD:
    file:     lib/Labyrinth/DIUtils/GD.pm
    version:  5.08

no_index:
  directory:
    - t

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-DIUtils-GD
  repository: http://github.com/barbie/labyrinth-diutils-gddriver

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
